### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by RandomAltThing** [Dan1ve/MaterialTabsListScrolling#6]
Android version: 4.2.2

The app crashes once I run it.

**Comment by Dan1ve** [comment]
Hi, I'm not really actively maintaining this repo, but could you give me some details about the crash?

**Comment by RandomAltThing** [comment]
@Dan1ve I forgot, let me look at the logcat

**Comment by RandomAltThing** [comment]
```

08-30 20:56:18.406 D/AndroidRuntime(18068): Shutting down VM
08-30 20:56:18.406 W/dalvikvm(18068): threadid=1: thread exiting with uncaught exception (group=0x40d8e930)
08-30 20:56:18.406 E/AndroidRuntime(18068): FATAL EXCEPTION: main
08-30 20:56:18.406 E/AndroidRuntime(18068): java.lang.RuntimeException: Unable to start activity ComponentInfo{de.veihelmann.example.materialtabsscrolling/de.veihelmann.example.materialtabsscrolling.MainActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2262)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at android.app.ActivityThread.access$700(ActivityThread.java:158)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at android.os.Looper.loop(Looper.java:176)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at android.app.ActivityThread.main(ActivityThread.java:5365)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at java.lang.reflect.Method.invokeNative(Native Method)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at java.lang.reflect.Method.invoke(Method.java:511)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at dalvik.system.NativeStart.main(Native Method)
08-30 20:56:18.406 E/AndroidRuntime(18068): Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:363)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at de.veihelmann.example.materialtabsscrolling.MainActivity.onCreate(MainActivity.java:18)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at android.app.Activity.performCreate(Activity.java:5326)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225)
08-30 20:56:18.406 E/AndroidRuntime(18068): 	... 11 more
```

**Comment by Dan1ve** [comment]
Thanks for the logcat, adding

<item name="windowNoTitle">true</item>

into the styles.xml should do the trick.
Would you mind trying that?

**Comment by RandomAltThing** [comment]
Yup, I will try that. Thanks.
